### PR TITLE
Fixed serialization in RbacCollector for ZDT

### PR DESCRIPTION
**Pull request by belgattitude**
Issue using Zend Developer Tools and ZfcRac.

### CODE REVIEW

**Comment by belgattitude** [comment]
Travis failed on PSR2, just tried to fix it.

**Comment by stephaun** [comment]
I don't think this has been fixed yet, so as a temporary solution I have made the following changes:
In ./module/Application/config/module.config.php:
```php
'view_manager' => array(
   'template_map' => array(
      // Temp fix until this is approved: https://github.com/ZF-Commons/zfc-rbac/pull/296
      'zend-developer-tools/toolbar/zfc-rbac' => __DIR__ . '/../view/zend-developer-tools/toolbar/zfc-rbac.phtml', 
   ),
),
```
Then copy the zfc-rbac.phtml file from the `./vendor` directory into `./module/Application/view/zend-developer-tools/toolbar` (note: `'Application'` in the `application.config.php` must be loaded _after_ `'ZfcRbac'`) 

In the newly created zfc-rbac.phtml , modify the top few lines to look like this:
```php
$this->collector->unserialize($this->collector->serialize());
/* @var $collection \ZfcRbac\Collector\RbacCollector */
$collection = $this->collector->getCollection();
```

**Comment by imonteiro** [comment]
:+1:

**Comment by countless-integers** [comment]
Will it be merged soon?

**Comment by bakura10** [comment]
I'm a bit unsure about this, I've not coded PHP project for months, and I've not used for ZDT for even more, so I'd prefer someone familiar with this to handle it. @danizord ?

**Comment by danizord** [comment]
Yeah I finally got some time to take a deep look into it. Thanks!

**Comment by guliano** [comment]
When it will be tagged and released?

**Comment by danizord** [comment]
@guliano [2.5.3](https://github.com/ZF-Commons/zfc-rbac/releases/tag/v2.5.3) released. Thank you guys   ;-)

**Pull request merged**
