### PR TITLE
Silence failing tests

### PR DESCRIPTION
**Pull request by basz**

### CODE REVIEW

**Comment by basz** [comment]
@bakura10 apparently travis is not running

**Comment by bakura10** [comment]
That's strange. It says the last commit from develop was 1 year ago :/. I'm checking.

**Comment by bakura10** [comment]
Travis was actually disabled (I don't know why). I've reactivated it.

**Comment by basz** [comment]
Thats a good way to have passing tests :)

**Comment by basz** [comment]
@bakura10 this PR simply silences some failing tests either by fixing or skipping them. 

pro/con merging this? I'll would like to rebase #315 on this

**Comment by bakura10** [comment]
Let's merge. We'll rewrite those later.

**Pull request merged**
