### PR TITLE
Register guards only for http requests

### PR DESCRIPTION
**Pull request by thestanislav**
Guards should not be registered for CLI applications

### CODE REVIEW

**Comment by danizord** [comment]
Not sure if this is mergeable, I think ZfcRbac guards are also usable in CLI env.

Ping @bakura10

**Comment by thestanislav** [comment]
But right now if any guard is set, for any cli applications we have "Don't have permission" error

**Comment by danizord** [comment]
@thestanislav You can solve this by authenticating some identity (e.g. some worker) when running the application from CLI or overriding `ZfcRbac\Guards` service factory to return an empty array.

If I merge this one, I could break some applications that relies on ZfcRbac to protect their CLI.

**Comment by bakura10** [comment]
This is definitely a BC break.

As danizord say, one option would be to authenticate your CLI requests. If you are using oauth token for instance, you could pass the key as part of your CLI requests to authenticate it.

As a side note, this is a reason why I prefer not to use guard, and only protect my controller directly. If you use guard or protect services, you run into this problem.

If you protect your controllers (which are the entry point of an API most of the time), then management become easier (as you'll have different controllers for console routes, where you can remove the check).

I'm therefore closing for now.

**Pull request closed without merging**
